import type { Metadata } from "next";
import "@/styles/main.css";
import { minSans } from "@/fonts";
import GlobalToast from "@/components/common/GlobalToast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${minSans.className} font-medium`}>
      <body>
        {children}
        <GlobalToast />
      </body>
    </html>
  );
}
